выполнил ДЗ №10
YakovMalykh/SkyCourse2_HW_4 pull request #5
Opened 2022-04-13 18:35 UTC by YakovMalykh

2022-04-13 19:01 UTC, OlgaLugacheva requested changes

2022-04-13 19:01 UTC, OlgaLugacheva commented on src/main/java/pro/sky/java/course2/skycourse2_hw_4/EmployeeService.java
> +            // чтобы это сообщение выводилось в консоль?
не поняла вопроса, sout если нужно для дебага

2022-04-14 06:19 UTC, YakovMalykh commented on src/main/java/pro/sky/java/course2/skycourse2_hw_4/EmployeeService.java
> +            // чтобы это сообщение выводилось в консоль?
Я имею в виду, чтобы если вводится недопустимый символ в браузере и выкидывается эта ошибка, в консоли бы вывелось сообщение "введены неверные символы", чтобы я понял что именно по этой причине выкинута ошибка, ведь BadRequestEmployeeException выбрасывается и при попытке добавить того-же сотрудника повторно (а в этом случае я хотел бы, чтобы в консоль вывелось "уже имеется такой сотрудник")

2022-04-14 14:39 UTC, OlgaLugacheva approved these changes

2022-04-28 10:46 UTC, merged